// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgentAssistant.Migrations
{
    [DbContext(typeof(AgentContext))]
    [Migration("20210525114920_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("AgentAssistant.Data.Entities.Volt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClosingCashMoney")
                        .HasColumnType("REAL");

                    b.Property<double>("ClosingLiquidMoney")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("OpeningCashMoney")
                        .HasColumnType("REAL");

                    b.Property<double>("OpeningLiquidMoney")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Volts");
                });
#pragma warning restore 612, 618
        }
    }
}
